version: '3.1'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - postgresdata:/var/lib/pgsql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  postgresdata:
